### ISSUE TITLE
_changes mock

### ISSUE THREAD

**Issue by jcrugzz** [chris-l/mock-couch#1]
Just came across this project, I am so glad this exists. Anything that requires having more than one couch becomes _real_ annoying to test. Specifically I've been wanting something like this in order to write some tests for [`overwatch`](https://github.com/nodejitsu/overwatch). I'd love to help out with a basic `_changes` implementation when I have some bandwidth. Let me know if this interests you :).

**Comment by chris-l** [comment]
Implemented here: #8.
