### ISSUE TITLE
Restify Error

### ISSUE THREAD

**Issue by conor-mac-aoidh** [chris-l/mock-couch#10]
When I run mock-couch I get an error:

```
    Stacktrace:
      TypeError: Object #<Object> has no method 'createsrv'
  at node_modules/mock-couch/index.js:21:23
```

I think it was introduced in this commit:

https://github.com/chris-l/mock-couch/commit/590c1e4b60b25b4c99b7935cfa9aa46fce59e8e4#diff-168726dbe96b3ce427e7fedce31bb0bcR21

Should be a quick fix!

**Comment by chris-l** [comment]
Oops! What a silly mistake, sorry. Fixed now.
Thanks!
