### ISSUE TITLE
When querying against multiple keys, rows.length will be at most equal to keys.length

### ISSUE THREAD

**Issue by reederz** [chris-l/mock-couch#31]
I'm talking about this block https://github.com/chris-l/mock-couch/blob/8793eeff62cd5e8e2d698a760f55469d99fcfac5/lib/query_options.js#L86-90 .

It maps elements of *keys* array to exactly one match from *rows* array.

**Comment by chris-l** [comment]
Yes, that was totally an error. Thanks a lot for your fix!
