### ISSUE TITLE
Add support for built-in reduce functions

### ISSUE THREAD

**Issue by reederz** [chris-l/mock-couch#33]
One of my tests broke today and it was because I was using **sum** function.

Reference of built-in reduce functions: https://wiki.apache.org/couchdb/Built-In_Reduce_Functions .

**Comment by chris-l** [comment]
Thanks for the report, I'll check it.

**Comment by chris-l** [comment]
Ok, this commit 84a7b94990c2978414eed7a2fc06efdc8aea47c6 fixes that. (and also `_count`)

Wait a couple of days (or less) for a release that has those changes.

**Comment by reederz** [comment]
Thanks!
