### ISSUE TITLE
support for _show and _list functions

### ISSUE THREAD

**Issue by osherx** [chris-l/mock-couch#35]
Great work!

Support in _show and _list functions would be lovely.

Thanks :)

**Comment by chris-l** [comment]
While is true that would be nice to have them, right now, it's not in my plans to add them. Perhaps I could add them after adding bulk attachment support.

But the fastest way to have them here is that you send me a PR :)

**Comment by osherx** [comment]
obviously.
being a busy person myself, I thought at this stage to just share the idea
and open the Feature-Request - maybe somebody will get to that before me :)



On Mon, Aug 17, 2015 at 9:43 PM, christopher luna <notifications@github.com>
wrote:

> While is true that would be nice to have them, right now, it's not in my
> plans to add them. Perhaps I could add them after adding bulk attachment
> support.
>
> But the fastest way to have them here is that you send me a PR :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/chris-l/mock-couch/issues/35#issuecomment-131921613>.
>



-- 
Osher E
+972-544-884821
