### ISSUE TITLE
Getting some errors with node v5.9.0

### ISSUE THREAD

**Issue by KingScooty** [chris-l/mock-couch#40]
I seem to be getting the following errors when trying to create a new mockCouch server.

```js
var mockCouch = require('mock-couch');
var couchdb = mockCouch.createServer();
```

```
{ [Error: Cannot find module './build/Release/DTraceProviderBindings'] code: 'MODULE_NOT_FOUND' }
{ [Error: Cannot find module './build/default/DTraceProviderBindings'] code: 'MODULE_NOT_FOUND' }
{ [Error: Cannot find module './build/Debug/DTraceProviderBindings'] code: 'MODULE_NOT_FOUND' }
```

Any ideas what would be causing this?

**Comment by KingScooty** [comment]
It appears `Restify` has an *optional* dependency called `dtrace-provider`, which doesn't seem to get installed when installing `mock-couch`.

**Comment by chris-l** [comment]
I can't replicate it. I'm using archlinux with node 5.9.0, and using the same line two lines as you, but have no problems.

**Comment by KingScooty** [comment]
Must be a dTrace issue with OS X then, as i've seen a few issues posted about it on the `dtrace-provider` page. I'll close this and chase them. It seems to be a non fatal error according to the issues over there.
