### ISSUE TITLE
Fix in 'Add put/post for design docs #42' Wasn't Delivered into NPM Package

### ISSUE THREAD

**Issue by RuizhiWang** [chris-l/mock-couch#45]
Hi there,
Can somebody publish the fix in 'Add put/post for design docs #42' to npm package?
The latest 0.1.6 version of npm package was published 6 month ago and doesn't have this fix.

Really look forward to seeing the npm package include this fix, rather than install from git for the specific version.

Thanks very much.

**Comment by chris-l** [comment]
Ok, done.
The new version is 0.1.7

**Comment by RuizhiWang** [comment]
@chris-l 
Hi Chris,
Thanks very much for your quick response, the new version 0.1.7 works, thanks.
