### ISSUE TITLE
I get this error when running my simple tests: The super constructor to inherits must not be null or undefined

### ISSUE THREAD

**Issue by ErnestoIslas** [chris-l/mock-couch#53]
This issue might not be related to **mock-couch** but I would appreciate some help. I am getting this error when running a simple test (let me know if you need the complete log):

```console
TypeError: The super constructor to "inherits" must not be null or undefined
  at Object.inherits (util.js:971:11)
  at Object.<anonymous> (node_modules\mock-couch\node_modules\spdy\lib\spdy\connection.js:86:6)
```

This is my simple test (I have deleted some lines; _mockedUsers_ is a simple JSON object):

```javascript
(function mockConnection(module, require) {
  'use strict';

  const path = require('path');
  const root = path.resolve('./');
  const mockedUsers = require(`${root}/mocks/users`);

  const should = require('should');
  const mock = require('mock-couch');

  describe('Mock couch connection', function mockCouchConnection() {
    let Users;
    let mockCouch;
    const port = 5984;
    const uid = 'acbdefg@us.ibm.com';

    beforeEach(function beforeEach() {
      mockCouch = mock.createServer({ keepAlive: false, });
      mockCouch.listen(port, function mockCouchListen() {
        // does nothing... yet!
      });
      // This creates a db for Mock Couch. The db is nothing but an array of objects.
      // If we provide an object with an _id property, it will use it. Otherwise, it will create a random one.
      Users = mockCouch.addDB('users', mockedUsers);
    });

    it(`user ${uid} must exist`, function userMustExists(done) {
      // TODO: validate that user actually exists.
      done();
    });
  });
}(module, require));
```

The error happens at this line `mockCouch = mock.createServer({ keepAlive: false, });`. I have run the code in different Nodejs versions, including **8.4.0**, **8.8.0**, **7.10.0**.

Thanks!

**Comment by jeremy-j-ackso** [comment]
I'm getting this issue too.

I think it's being caused by the version of `spdy` in use in the version of `restify` that's in use in the package based on this issue in `restify`: https://github.com/restify/node-restify/issues/1259

This package seems to rely on `restify@>=2.7.0 <3.0.0`.

**Comment by simonbruneaud** [comment]
After some investigation, it seems that the problem come from Node versions.
With node versions < **7.x** it works - I tried it with the 6.9.1 and **5.5.5**

I'll make a pull request @chris-l

**Comment by bfabec** [comment]
We are having the same issue on 8.9.4, any updates on this yet?

**Comment by gamegee** [comment]
The fix I've made is supposed to work.
You can just fork it #54

**Comment by gamegee** [comment]
@chris-l

**Comment by cnguyenp** [comment]
this issue still exists on node 8.9.3 of mime.  any ideas why this happens? Thanks

**Comment by chris-l** [comment]
It seems the problem was that I forgot to update the shrinkwrap. So even with gamegee patch, it was still using the old version of restify.

Sorry about that! So I have update it now. Try again with the new version of mock-couch.
