### ISSUE TITLE
No need for npm-shrinkwrap.json to be included in repo

### ISSUE THREAD

**Issue by cnguyenp** [chris-l/mock-couch#56]
This would be ignored because it causes the repo to install whatever version of restify in it.
restify is currently 6.4.3 but npm-shrinkwrap.json still refers to 2.8.5.

**Comment by chris-l** [comment]
npm-shrinkwrap.json is purposely included to force the working version of the dependencies. Problem was, I forgot to update it! XD

Sorry about that!

I have updated it on the latest version and it should use the new version of restify now.
